# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Типы проектов

# Model Form Field configuration
form: $/bree7e/cris/models/projecttype/fields.yaml

# Model Class name
modelClass: Bree7e\Cris\Models\ProjectType

# Default redirect location
defaultRedirect: bree7e/cris/projecttypes

# Create page
create:
    title: Создать тип проекта
    redirect: bree7e/cris/projecttypes/update/:id
    redirectClose: bree7e/cris/projecttypes

# Update page
update:
    title: Редактировать тип проекта
    redirect: bree7e/cris/projecttypes
    redirectClose: bree7e/cris/projecttypes

# Preview page
preview:
    title: Просмотр типа проекта
